"""The application's embedded license-verification public key.

Only the *public* key ships with the application — it can verify a
signature but cannot produce one. The matching private key is held
solely by the vendor: either auto-created on first use by the
Developer Suite (see
:attr:`developer_suite.config.DeveloperSuiteConfig.licensing_private_key_path`
and :func:`licensing.crypto.signing.ensure_keypair`), or generated by
hand with :mod:`licensing.license_generator`'s offline CLI — either
way, never committed to version control (``.gitignore`` excludes any
``*private_key.pem`` under ``licensing/vendor/``) and never present on
a customer's Attendance Client installation. This asymmetric split is
what makes a license key unforgeable even though every line of this
application's verification code is visible to anyone who has installed
it: knowing exactly how a signature is checked does not let you
produce a new valid one without the private key.

Re-keyed once, deliberately: the private key matching this module's
previous ``PUBLIC_KEY_PEM`` was generated in an early development
session before the Developer Suite existed to hold it at a stable
location, and was never persisted anywhere retrievable (correctly, per
the ``.gitignore`` rule above) — so it was lost before any customer was
ever issued a license under it. This is therefore a safe, one-time
re-key with nothing to invalidate, not the "deliberate, coordinated
re-key of a keypair already in use" this module's own next paragraph
warns against for every re-key *after* this one.
"""

from __future__ import annotations

from cryptography.hazmat.primitives.serialization import load_pem_public_key
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

PUBLIC_KEY_PEM: bytes = b"""-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA474EQ0M+3o/FJ5vihDqecIAnYHY905bw085Te6gKxmg=
-----END PUBLIC KEY-----
"""
"""PEM-encoded Ed25519 public key, generated once for this application.

Regenerating this keypair (see ``licensing/license_generator.py
--generate-keypair``) immediately invalidates every license key issued
under the previous one - only do so as a deliberate, coordinated
re-key, never casually.
"""


def load_public_key() -> Ed25519PublicKey:
    """Parse :data:`PUBLIC_KEY_PEM` into a usable key object.

    Returns:
        The application's Ed25519 public key, for signature
        verification only.
    """
    key = load_pem_public_key(PUBLIC_KEY_PEM)
    if not isinstance(key, Ed25519PublicKey):
        raise TypeError(
            f"Expected an Ed25519 public key, got {type(key).__name__}. "
            "PUBLIC_KEY_PEM is misconfigured."
        )
    return key
