"""add attendance client subscription-check bookkeeping table

Revision ID: 80c7558c5e4d
Revises: 551b9791696c
Create Date: 2026-08-04 19:15:33.621960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# UTCDateTime -- see alembic/versions/f945cdc05edd_baseline_schema.py.
import models.base


# revision identifiers, used by Alembic.
revision: str = '80c7558c5e4d'
down_revision: Union[str, None] = '551b9791696c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_subscription_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('subscription_end_date', sa.Date(), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('checked_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_subscription_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_subscription_state')
    # ### end Alembic commands ###
