"""add payroll module

Revision ID: 814404e2642c
Revises: 8f558f3b5277
Create Date: 2026-08-07 18:53:14.664891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# UTCDateTime / EncryptedDecimal -- see
# alembic/versions/f945cdc05edd_baseline_schema.py.
import models.base
import models.encrypted_types


# revision identifiers, used by Alembic.
revision: str = '814404e2642c'
down_revision: Union[str, None] = '8f558f3b5277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_automatic_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('late', 'early_leave', 'absence', 'missing_punch', 'overtime', name='payroll_auto_rule_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('calculation_method', sa.Enum('fixed_amount', 'per_minute', 'per_hour', 'half_day', 'full_day', 'percentage_of_daily_salary', name='payroll_calculation_method_enum', native_enum=False, length=32), nullable=False),
    sa.Column('value', models.encrypted_types.EncryptedDecimal(length=512), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_automatic_rules_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payroll_automatic_rules_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_payroll_automatic_rules_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_automatic_rules')),
    sa.UniqueConstraint('company_id', 'rule_type', name='uq_payroll_automatic_rules_company_rule_type')
    )
    op.create_index(op.f('ix_payroll_automatic_rules_company_id'), 'payroll_automatic_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_automatic_rules_is_deleted'), 'payroll_automatic_rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payroll_automatic_rules_public_id'), 'payroll_automatic_rules', ['public_id'], unique=True)
    op.create_index(op.f('ix_payroll_automatic_rules_rule_type'), 'payroll_automatic_rules', ['rule_type'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'reviewed', 'finalized', name='payroll_run_status_enum', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('finalized_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finalized_by_id', sa.Integer(), nullable=True),
    sa.Column('reopened_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reopened_by_id', sa.Integer(), nullable=True),
    sa.Column('run_version', sa.Integer(), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name=op.f('ck_payroll_runs_ck_payroll_runs_month_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_runs_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payroll_runs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['users.id'], name=op.f('fk_payroll_runs_finalized_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reopened_by_id'], ['users.id'], name=op.f('fk_payroll_runs_reopened_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_payroll_runs_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_runs')),
    sa.UniqueConstraint('company_id', 'year', 'month', name='uq_payroll_runs_company_period')
    )
    op.create_index(op.f('ix_payroll_runs_company_id'), 'payroll_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_is_deleted'), 'payroll_runs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payroll_runs_month'), 'payroll_runs', ['month'], unique=False)
    op.create_index(op.f('ix_payroll_runs_public_id'), 'payroll_runs', ['public_id'], unique=True)
    op.create_index(op.f('ix_payroll_runs_status'), 'payroll_runs', ['status'], unique=False)
    op.create_index(op.f('ix_payroll_runs_year'), 'payroll_runs', ['year'], unique=False)
    op.create_table('payroll_run_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('run_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('finalized_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finalized_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_run_snapshots_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payroll_run_snapshots_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['users.id'], name=op.f('fk_payroll_run_snapshots_finalized_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], name=op.f('fk_payroll_run_snapshots_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_payroll_run_snapshots_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_run_snapshots')),
    sa.UniqueConstraint('payroll_run_id', 'run_version', name='uq_payroll_run_snapshots_run_version')
    )
    op.create_index(op.f('ix_payroll_run_snapshots_company_id'), 'payroll_run_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_run_snapshots_is_deleted'), 'payroll_run_snapshots', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payroll_run_snapshots_payroll_run_id'), 'payroll_run_snapshots', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_run_snapshots_public_id'), 'payroll_run_snapshots', ['public_id'], unique=True)
    op.create_table('payroll_run_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', models.encrypted_types.EncryptedDecimal(length=512), nullable=False),
    sa.Column('working_days_in_period', sa.Integer(), nullable=False),
    sa.Column('attendance_days', sa.Integer(), nullable=False),
    sa.Column('absence_days', sa.Integer(), nullable=False),
    sa.Column('missing_punch_days', sa.Integer(), nullable=False),
    sa.Column('late_minutes_total', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes_total', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes_total', sa.Integer(), nullable=False),
    sa.Column('automatic_deduction_total', models.encrypted_types.EncryptedDecimal(length=512), nullable=False),
    sa.Column('manual_deduction_total', models.encrypted_types.EncryptedDecimal(length=512), nullable=False),
    sa.Column('bonus_total', models.encrypted_types.EncryptedDecimal(length=512), nullable=False),
    sa.Column('net_salary', models.encrypted_types.EncryptedDecimal(length=512), nullable=False),
    sa.Column('computed_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_run_lines_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payroll_run_lines_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_run_lines_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], name=op.f('fk_payroll_run_lines_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_payroll_run_lines_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_run_lines')),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payroll_run_lines_run_employee')
    )
    op.create_index(op.f('ix_payroll_run_lines_company_id'), 'payroll_run_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_run_lines_employee_id'), 'payroll_run_lines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_run_lines_is_deleted'), 'payroll_run_lines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payroll_run_lines_payroll_run_id'), 'payroll_run_lines', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_run_lines_public_id'), 'payroll_run_lines', ['public_id'], unique=True)
    op.create_table('payroll_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('deduction', 'bonus', name='payroll_adjustment_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('automatic', 'manual', name='payroll_adjustment_source_enum', native_enum=False, length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('amount', models.encrypted_types.EncryptedDecimal(length=512), nullable=False),
    sa.Column('reason_category', sa.String(length=50), nullable=True),
    sa.Column('reason_text', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('source_attendance_record_id', sa.Integer(), nullable=True),
    sa.Column('calculation_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name=op.f('ck_payroll_adjustments_ck_payroll_adjustments_month_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_adjustments_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payroll_adjustments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_adjustments_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_attendance_record_id'], ['attendance_records.id'], name=op.f('fk_payroll_adjustments_source_attendance_record_id_attendance_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_payroll_adjustments_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_adjustments'))
    )
    op.create_index(op.f('ix_payroll_adjustments_adjustment_type'), 'payroll_adjustments', ['adjustment_type'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_company_id'), 'payroll_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_employee_id'), 'payroll_adjustments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_is_deleted'), 'payroll_adjustments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_month'), 'payroll_adjustments', ['month'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_public_id'), 'payroll_adjustments', ['public_id'], unique=True)
    op.create_index(op.f('ix_payroll_adjustments_source'), 'payroll_adjustments', ['source'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_year'), 'payroll_adjustments', ['year'], unique=False)
    op.add_column('company_settings', sa.Column('payroll_working_days_per_month', sa.Integer(), server_default='26', nullable=False))
    op.add_column('company_settings', sa.Column('payroll_working_hours_per_day', sa.Numeric(precision=4, scale=2), server_default='8.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'payroll_working_hours_per_day')
    op.drop_column('company_settings', 'payroll_working_days_per_month')
    op.drop_index(op.f('ix_payroll_adjustments_year'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_source'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_public_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_month'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_is_deleted'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_employee_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_company_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_adjustment_type'), table_name='payroll_adjustments')
    op.drop_table('payroll_adjustments')
    op.drop_index(op.f('ix_payroll_run_lines_public_id'), table_name='payroll_run_lines')
    op.drop_index(op.f('ix_payroll_run_lines_payroll_run_id'), table_name='payroll_run_lines')
    op.drop_index(op.f('ix_payroll_run_lines_is_deleted'), table_name='payroll_run_lines')
    op.drop_index(op.f('ix_payroll_run_lines_employee_id'), table_name='payroll_run_lines')
    op.drop_index(op.f('ix_payroll_run_lines_company_id'), table_name='payroll_run_lines')
    op.drop_table('payroll_run_lines')
    op.drop_index(op.f('ix_payroll_run_snapshots_public_id'), table_name='payroll_run_snapshots')
    op.drop_index(op.f('ix_payroll_run_snapshots_payroll_run_id'), table_name='payroll_run_snapshots')
    op.drop_index(op.f('ix_payroll_run_snapshots_is_deleted'), table_name='payroll_run_snapshots')
    op.drop_index(op.f('ix_payroll_run_snapshots_company_id'), table_name='payroll_run_snapshots')
    op.drop_table('payroll_run_snapshots')
    op.drop_index(op.f('ix_payroll_runs_year'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_status'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_public_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_month'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_is_deleted'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_company_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_payroll_automatic_rules_rule_type'), table_name='payroll_automatic_rules')
    op.drop_index(op.f('ix_payroll_automatic_rules_public_id'), table_name='payroll_automatic_rules')
    op.drop_index(op.f('ix_payroll_automatic_rules_is_deleted'), table_name='payroll_automatic_rules')
    op.drop_index(op.f('ix_payroll_automatic_rules_company_id'), table_name='payroll_automatic_rules')
    op.drop_table('payroll_automatic_rules')
    # ### end Alembic commands ###
