"""add palm_registered to employees

Revision ID: b67c2f1e50c5
Revises: 814404e2642c
Create Date: 2026-08-08 03:08:10.904336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67c2f1e50c5'
down_revision: Union[str, None] = '814404e2642c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('palm_registered', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'palm_registered')
    # ### end Alembic commands ###
