"""baseline schema

The full v1.0.0 schema, captured as a single baseline revision since no
Alembic-managed migration existed before this release (the app has
always created its schema directly via
``Database.create_all_tables()`` -> ``Base.metadata.create_all()``).
A fresh deployment runs this migration normally; an existing SQLite
deployment already on the equivalent schema should be stamped onto it
instead of re-run (see ``alembic/README.md``):

    alembic stamp f945cdc05edd

Revision ID: f945cdc05edd
Revises:
Create Date: 2026-08-02 09:06:48.404546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate detects these custom TypeDecorators (see models/base.py's
# UTCDateTime and models/encrypted_types.py's EncryptedString/
# EncryptedDecimal) but does not import them automatically - added by
# hand so this migration is actually runnable, not just readable.
import models.base
import models.encrypted_types


# revision identifiers, used by Alembic.
revision: str = 'f945cdc05edd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=250), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_companies_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_companies_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_companies_name'))
    )
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_companies_public_id'), 'companies', ['public_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_roles_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_roles_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_roles_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('company_id', 'name', name='uq_roles_company_id_name')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_index(op.f('ix_roles_company_id'), 'roles', ['company_id'], unique=False)
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_public_id'), 'roles', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=2), server_default='ar', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("preferred_language IN ('ar', 'en')", name=op.f('ck_users_ck_users_preferred_language')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_users_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('company_id', 'email', name='uq_users_company_id_email'),
    sa.UniqueConstraint('company_id', 'username', name='uq_users_company_id_username')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('login', 'logout', 'login_failed', 'create', 'update', 'delete', 'restore', 'export', 'backup', 'restore_backup', 'device_sync', name='audit_action_enum', native_enum=False, length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_audit_logs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_audit_logs_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_company_id_created_at', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_logs_public_id'), 'audit_logs', ['public_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_main_branch', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_branches_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_branches_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('company_id', 'code', name='uq_branches_company_id_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_branches_company_id_name')
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_branches_is_deleted'), 'branches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_branches_public_id'), 'branches', ['public_id'], unique=True)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), server_default='ar', nullable=False),
    sa.Column('theme', sa.String(length=5), server_default='light', nullable=False),
    sa.Column('date_format', sa.String(length=20), server_default='%d/%m/%Y', nullable=False),
    sa.Column('time_format_24h', sa.Boolean(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='IQD', nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('timezone_name', sa.String(length=50), server_default='Asia/Baghdad', nullable=False),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_interval_hours', sa.Integer(), nullable=False),
    sa.Column('backup_retention_count', sa.Integer(), nullable=False),
    sa.Column('default_device_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('default_sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("language IN ('ar', 'en')", name=op.f('ck_company_settings_ck_company_settings_language')),
    sa.CheckConstraint("theme IN ('light', 'dark')", name=op.f('ck_company_settings_ck_company_settings_theme')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_settings_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_company_settings_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_company_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_settings')),
    sa.UniqueConstraint('company_id', name='uq_company_settings_company_id')
    )
    op.create_index(op.f('ix_company_settings_company_id'), 'company_settings', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_settings_is_deleted'), 'company_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_settings_public_id'), 'company_settings', ['public_id'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('parent_department_id IS NULL OR parent_department_id != id', name=op.f('ck_departments_ck_departments_no_self_parent')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_departments_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_departments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], name=op.f('fk_departments_parent_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_departments_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('company_id', 'code', name='uq_departments_company_id_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_departments_company_id_name')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=False)
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_departments_parent_department_id'), 'departments', ['parent_department_id'], unique=False)
    op.create_index(op.f('ix_departments_public_id'), 'departments', ['public_id'], unique=True)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('is_recurring_annually', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_holidays_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_holidays_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_holidays_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('company_id', 'holiday_date', 'name', name='uq_holidays_company_id_date_name')
    )
    op.create_index(op.f('ix_holidays_company_id'), 'holidays', ['company_id'], unique=False)
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('ix_holidays_is_deleted'), 'holidays', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_holidays_public_id'), 'holidays', ['public_id'], unique=True)
    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('annual', 'sick', 'emergency', 'unpaid', 'other', name='leave_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('annual_entitlement_days', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_policies_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_leave_policies_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_leave_policies_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_policies')),
    sa.UniqueConstraint('company_id', 'leave_type', name='uq_leave_policies_company_id_leave_type')
    )
    op.create_index(op.f('ix_leave_policies_company_id'), 'leave_policies', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_policies_is_deleted'), 'leave_policies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leave_policies_leave_type'), 'leave_policies', ['leave_type'], unique=False)
    op.create_index(op.f('ix_leave_policies_public_id'), 'leave_policies', ['public_id'], unique=True)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=True),
    sa.Column('max_branches', sa.Integer(), nullable=True),
    sa.Column('enabled_features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_licenses_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_licenses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_licenses_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    op.create_index(op.f('ix_licenses_company_id'), 'licenses', ['company_id'], unique=False)
    op.create_index(op.f('ix_licenses_is_deleted'), 'licenses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_index(op.f('ix_licenses_public_id'), 'licenses', ['public_id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_permissions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_permissions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_is_deleted'), 'permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_index(op.f('ix_permissions_public_id'), 'permissions', ['public_id'], unique=True)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shifts_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_shifts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_shifts_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('company_id', 'name', name='uq_shifts_company_id_name')
    )
    op.create_index(op.f('ix_shifts_company_id'), 'shifts', ['company_id'], unique=False)
    op.create_index(op.f('ix_shifts_is_deleted'), 'shifts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shifts_public_id'), 'shifts', ['public_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('protocol', sa.Enum('zkteco_tcp', 'zkteco_udp', 'hikvision', name='device_protocol_enum', native_enum=False, length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('communication_key', models.encrypted_types.EncryptedString(length=512), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'error', 'unknown', name='device_status_enum', native_enum=False, length=32), nullable=False),
    sa.Column('last_seen_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('port > 0 AND port <= 65535', name=op.f('ck_devices_ck_devices_port_range')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_devices_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_devices_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_devices_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_devices_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('company_id', 'host', 'port', name='uq_devices_company_id_host_port'),
    sa.UniqueConstraint('company_id', 'name', name='uq_devices_company_id_name')
    )
    op.create_index(op.f('ix_devices_branch_id'), 'devices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_devices_company_id'), 'devices', ['company_id'], unique=False)
    op.create_index(op.f('ix_devices_is_deleted'), 'devices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_devices_protocol'), 'devices', ['protocol'], unique=False)
    op.create_index(op.f('ix_devices_public_id'), 'devices', ['public_id'], unique=True)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('salary', models.encrypted_types.EncryptedDecimal(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('employment_status', sa.Enum('active', 'on_leave', 'suspended', 'resigned', 'terminated', name='employment_status_enum', native_enum=False, length=32), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('qr_code_path', sa.String(length=500), nullable=True),
    sa.Column('barcode_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_employees_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employees_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employees_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('company_id', 'email', name='uq_employees_company_id_email'),
    sa.UniqueConstraint('company_id', 'employee_number', name='uq_employees_company_id_employee_number'),
    sa.UniqueConstraint('company_id', 'national_id', name='uq_employees_company_id_national_id')
    )
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=False)
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_is_deleted'), 'employees', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employees_national_id'), 'employees', ['national_id'], unique=False)
    op.create_index(op.f('ix_employees_public_id'), 'employees', ['public_id'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('present', 'late', 'early_leave', 'absent', 'on_leave', 'holiday', 'weekend', name='attendance_day_status_enum', native_enum=False, length=32), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('early_leave_minutes >= 0', name=op.f('ck_attendance_records_ck_attendance_records_early_leave_minutes')),
    sa.CheckConstraint('late_minutes >= 0', name=op.f('ck_attendance_records_ck_attendance_records_late_minutes')),
    sa.CheckConstraint('overtime_minutes >= 0', name=op.f('ck_attendance_records_ck_attendance_records_overtime_minutes')),
    sa.CheckConstraint('worked_minutes >= 0', name=op.f('ck_attendance_records_ck_attendance_records_worked_minutes')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_attendance_records_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_attendance_records_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_records_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_attendance_records_shift_id_shifts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_attendance_records_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('company_id', 'employee_id', 'work_date', name='uq_attendance_records_company_employee_work_date')
    )
    op.create_index(op.f('ix_attendance_records_company_id'), 'attendance_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_is_deleted'), 'attendance_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_records_public_id'), 'attendance_records', ['public_id'], unique=True)
    op.create_index(op.f('ix_attendance_records_shift_id'), 'attendance_records', ['shift_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_status'), 'attendance_records', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_records_work_date'), 'attendance_records', ['work_date'], unique=False)
    op.create_table('employee_shift_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_employee_shift_assignments_ck_employee_shift_assignments_valid_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employee_shift_assignments_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_shift_assignments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_shift_assignments_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_employee_shift_assignments_shift_id_shifts')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_shift_assignments_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_shift_assignments'))
    )
    op.create_index(op.f('ix_employee_shift_assignments_company_id'), 'employee_shift_assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_employee_id'), 'employee_shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_is_deleted'), 'employee_shift_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_public_id'), 'employee_shift_assignments', ['public_id'], unique=True)
    op.create_index(op.f('ix_employee_shift_assignments_shift_id'), 'employee_shift_assignments', ['shift_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_policy_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status_enum', native_enum=False, length=32), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('days_count > 0', name=op.f('ck_leave_requests_ck_leave_requests_days_count_positive')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_leave_requests_ck_leave_requests_valid_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_requests_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_leave_requests_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_policy_id'], ['leave_policies.id'], name=op.f('fk_leave_requests_leave_policy_id_leave_policies')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_leave_requests_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_leave_requests_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_end_date'), 'leave_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_is_deleted'), 'leave_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_policy_id'), 'leave_requests', ['leave_policy_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_public_id'), 'leave_requests', ['public_id'], unique=True)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_table('attendance_punches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('attendance_record_id', sa.Integer(), nullable=True),
    sa.Column('punch_type', sa.Enum('check_in', 'check_out', name='punch_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('manual', 'device', 'api', name='attendance_source_enum', native_enum=False, length=32), nullable=False),
    sa.Column('punch_time', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('device_user_reference', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], name=op.f('fk_attendance_punches_attendance_record_id_attendance_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_attendance_punches_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_attendance_punches_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_attendance_punches_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_punches_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_attendance_punches_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_punches')),
    sa.UniqueConstraint('company_id', 'employee_id', 'device_id', 'punch_time', name='uq_attendance_punches_dedup')
    )
    op.create_index(op.f('ix_attendance_punches_attendance_record_id'), 'attendance_punches', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_company_id'), 'attendance_punches', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_device_id'), 'attendance_punches', ['device_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_employee_id'), 'attendance_punches', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_is_deleted'), 'attendance_punches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_punches_public_id'), 'attendance_punches', ['public_id'], unique=True)
    op.create_index(op.f('ix_attendance_punches_punch_time'), 'attendance_punches', ['punch_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_punches_punch_time'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_public_id'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_is_deleted'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_employee_id'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_device_id'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_company_id'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_attendance_record_id'), table_name='attendance_punches')
    op.drop_table('attendance_punches')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_public_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_policy_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_is_deleted'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_employee_shift_assignments_shift_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_public_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_is_deleted'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_employee_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_company_id'), table_name='employee_shift_assignments')
    op.drop_table('employee_shift_assignments')
    op.drop_index(op.f('ix_attendance_records_work_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_status'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_shift_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_public_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_is_deleted'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_company_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_employees_public_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_national_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_deleted'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_public_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_protocol'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_deleted'), table_name='devices')
    op.drop_index(op.f('ix_devices_company_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_branch_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_shifts_public_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_is_deleted'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_company_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_permissions_public_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_is_deleted'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_licenses_public_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_is_deleted'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_company_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_leave_policies_public_id'), table_name='leave_policies')
    op.drop_index(op.f('ix_leave_policies_leave_type'), table_name='leave_policies')
    op.drop_index(op.f('ix_leave_policies_is_deleted'), table_name='leave_policies')
    op.drop_index(op.f('ix_leave_policies_company_id'), table_name='leave_policies')
    op.drop_table('leave_policies')
    op.drop_index(op.f('ix_holidays_public_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_is_deleted'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_company_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_departments_public_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_parent_department_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_company_settings_public_id'), table_name='company_settings')
    op.drop_index(op.f('ix_company_settings_is_deleted'), table_name='company_settings')
    op.drop_index(op.f('ix_company_settings_company_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_branches_public_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_is_deleted'), table_name='branches')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_public_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_company_id_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_public_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_index(op.f('ix_roles_company_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_companies_public_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
