"""Validates this installation's subscription with the Attendance Server at login.

The server-managed replacement for the retired file-based license
system (see :mod:`licensing`, being removed): rather than verifying a
locally-stored, signed license file, this service asks the Attendance
Server directly, via :meth:`~sync.coordinator.ClientSyncCoordinator.get_subscription_status`,
and caches the last *server-confirmed* answer locally (see
:mod:`models.subscription_state`) purely so a temporarily unreachable
server does not lock a paying customer out.

Also owns this installation's fully-automatic, company-code-driven
first-time enrollment (see :meth:`resolve_company_code`/
:meth:`_auto_enroll`): this server is multi-tenant, so the Attendance
Client never displays or lets a user pick from a list of companies —
instead, the administrator hands each of that company's employees a
unique, opaque company code (e.g. ``FUTURELINE-7X4K9P``, generated by
the Developer Suite — see :class:`~server.models.subscription.Subscription`).
On first startup, the login screen collects that code alongside the
usual username/password (see :mod:`ui.login_window`); this service
resolves the code against the server *before* local authentication
even runs (only the server knows which company a code belongs to),
then the composition root authenticates the typed username/password
locally, against whichever local company the resolved name matches,
exactly as before. Only on that local authentication succeeding does
:meth:`confirm_local_binding` permanently bind this device to that
company (see
:meth:`~repositories.sync_repository.ClientSyncCredentialRepository.set_bound_company`),
so every future login skips the company code prompt entirely — see
:mod:`ui.login_window` for the exact bound-vs-unbound branching, and
``ui.settings`` for the administrator-only action that resets this
binding to allow a different code.

Grace period: if the server cannot be reached, this installation is
allowed to keep running for a bounded window (:data:`DEFAULT_GRACE_PERIOD`,
7 days) since the last successful check. The moment the server answers
again, its answer is authoritative immediately -- an explicit
suspended or expired verdict always applies right away, regardless of
any grace period remaining. Grace only ever covers "the server could
not be reached," never "the server said no."
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from enum import Enum

from database.database import Database
from models.subscription_state import ClientSubscriptionState
from repositories.subscription_state_repository import ClientSubscriptionStateRepository
from repositories.sync_repository import ClientSyncCredentialRepository
from sync.client import (
    DeviceRegistrationRejectedError,
    MaxDevicesReachedError,
    SubscriptionStatusResult,
    SyncClientError,
)
from sync.coordinator import ClientSyncCoordinator, DeviceNotEnrolledError

#: How long this installation may keep running on a cached, previously
#: server-confirmed subscription status after the server becomes
#: unreachable, before it must block.
DEFAULT_GRACE_PERIOD = timedelta(days=7)


class SubscriptionCheckOutcome(str, Enum):
    """Why :meth:`SubscriptionCheckService.check` reached its verdict."""

    VALID = "valid"
    EXPIRED = "expired"
    SUSPENDED = "suspended"
    NOT_REGISTERED = "not_registered"
    MAX_DEVICES_REACHED = "max_devices_reached"
    INVALID_COMPANY_CODE = "invalid_company_code"
    UNREACHABLE_WITHIN_GRACE = "unreachable_within_grace"
    UNREACHABLE_BLOCKED = "unreachable_blocked"


@dataclass(frozen=True)
class SubscriptionCheckResult:
    """The outcome of one :meth:`SubscriptionCheckService.check` call.

    Attributes:
        outcome: The specific reason behind :attr:`allowed`.
        allowed: Whether this installation may proceed to the rest of
            startup.
        message_ar: A clear, user-facing Arabic message — this
            application's primary UI language.
        message_en: The same message in English, for logs.
        company_name: The subscription's company name, if known.
        days_remaining: Days remaining until expiry, if known.
    """

    outcome: SubscriptionCheckOutcome
    allowed: bool
    message_ar: str
    message_en: str
    company_name: str | None = None
    days_remaining: int | None = None


@dataclass(frozen=True)
class CompanyCodeResolution:
    """The outcome of one :meth:`SubscriptionCheckService.resolve_company_code` call.

    Attributes:
        company_name: The resolved company's display name, for the
            caller to look up the matching *local* company by — set
            only when :attr:`blocked` is ``None``.
        blocked: Set instead of :attr:`company_name` if the code could
            not be resolved (invalid/inactive code, device cap
            reached, or the server was unreachable) — the caller shows
            :attr:`~SubscriptionCheckResult.message_ar` and stops
            before ever attempting local authentication.
    """

    company_name: str | None = None
    blocked: SubscriptionCheckResult | None = None


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _as_aware_utc(value: datetime) -> datetime:
    """Treat a naive timestamp (e.g. read back from SQLite) as UTC."""
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)


class SubscriptionCheckService:
    """Checks this installation's subscription status, with a bounded offline grace period."""

    def __init__(
        self,
        database: Database,
        sync_coordinator: ClientSyncCoordinator,
        *,
        device_name: str = "Attendance Client",
        grace_period: timedelta = DEFAULT_GRACE_PERIOD,
    ) -> None:
        """Create a check service bound to ``database`` and ``sync_coordinator``.

        Args:
            database: The Attendance Client's own database, where the
                last server-confirmed status is cached.
            sync_coordinator: Sync coordinator, enrolled or not — if
                not yet enrolled, :meth:`resolve_company_code` enrolls
                it automatically (see :meth:`_auto_enroll`).
            device_name: A human-readable label for this installation,
                used only for automatic first-time enrollment.
            grace_period: How long a cached, previously-confirmed
                status remains valid once the server becomes
                unreachable.
        """
        self._database = database
        self._sync_coordinator = sync_coordinator
        self._device_name = device_name
        self._grace_period = grace_period

    def get_cached(self) -> ClientSubscriptionState | None:
        """Return the last server-confirmed subscription state, without contacting the server.

        For display purposes only (e.g.
        :class:`~ui.subscription_info_window.SubscriptionInfoWindow`'s
        detail fields) — :meth:`check` is what actually re-verifies.
        """
        with self._database.session_scope() as session:
            return ClientSubscriptionStateRepository(session).get()

    def check(self) -> SubscriptionCheckResult:
        """Check this installation's already-established subscription status.

        Assumes this device has already enrolled — if not, returns
        :attr:`SubscriptionCheckOutcome.NOT_REGISTERED` immediately
        without contacting the server (see :meth:`resolve_company_code`
        for the first-time, login-driven enrollment step). Otherwise always
        reaches out to the server first; only falls back to the
        cached, last-confirmed status (subject to the grace period) if
        the server cannot be reached at all.
        """
        if not self._sync_coordinator.is_enrolled():
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.NOT_REGISTERED,
                allowed=False,
                message_ar="لم يتم تسجيل هذا الجهاز بعد. يرجى تسجيل الدخول أولاً لإتمام التسجيل التلقائي.",
                message_en=(
                    "This installation has not registered yet. Please log in first to "
                    "complete automatic registration."
                ),
            )

        try:
            status = self._sync_coordinator.get_subscription_status()
        except (SyncClientError, DeviceNotEnrolledError):
            return self._evaluate_grace()

        with self._database.session_scope() as session:
            ClientSubscriptionStateRepository(session).save(
                status=status.status,
                company_name=status.company_name,
                subscription_end_date=status.subscription_end_date,
                max_devices=status.max_devices,
                days_remaining=status.days_remaining,
            )

        return self._result_from_live_status(status)

    def resolve_company_code(self, *, company_code: str) -> CompanyCodeResolution:
        """Resolve a company code with the server, self-registering this device if needed.

        Called by the login screen *before* local username/password
        authentication, for a device not yet bound to any company (see
        :mod:`ui.login_window`) — only the server knows which company a
        code belongs to, so this step must happen first. Never shown,
        and never called, once :meth:`~repositories.sync_repository.ClientSyncCredentialRepository.get_bound_company_id`
        returns non-``None`` — that installation's login screen skips
        straight to :meth:`check` instead.

        If this device already holds server credentials (e.g. a prior
        attempt registered successfully but local authentication then
        failed), reuses them rather than registering a second device
        for the same installation — safe to call repeatedly while the
        user retries their username/password.

        Args:
            company_code: The code exactly as the user typed it.

        Returns:
            The resolved company name to look up locally, or a
            blocking result to show and stop at.
        """
        if self._sync_coordinator.is_enrolled():
            result = self.check()
            if not result.allowed:
                return CompanyCodeResolution(blocked=result)
            return CompanyCodeResolution(company_name=result.company_name)

        enrollment_failure = self._auto_enroll(company_code)
        if enrollment_failure is not None:
            return CompanyCodeResolution(blocked=enrollment_failure)

        status_result = self.check()
        if not status_result.allowed:
            return CompanyCodeResolution(blocked=status_result)
        return CompanyCodeResolution(company_name=status_result.company_name)

    def confirm_local_binding(self, *, company_id: int, company_code: str) -> None:
        """Permanently bind this device to ``company_id``, after local authentication succeeds.

        Called once, right after :meth:`resolve_company_code` returned
        a company name and the composition root then successfully
        authenticated the typed username/password against the
        matching local company (see :mod:`ui.login_window`). From this
        point on, this installation serves only that company — the
        login screen stops asking for a company code, and :meth:`check`
        alone governs every future subscription check.

        Args:
            company_id: The local company the user just authenticated
                into.
            company_code: The code that resolved to it, kept for
                display in the administrator settings screen.
        """
        with self._database.session_scope() as session:
            ClientSyncCredentialRepository(session).set_bound_company(
                company_id, company_code=company_code
            )

    def get_company_code(self) -> str | None:
        """Return the company code this installation is currently bound with, or ``None``."""
        with self._database.session_scope() as session:
            return ClientSyncCredentialRepository(session).get_company_code()

    def reset_enrollment(self) -> None:
        """Forget this installation's enrollment entirely (administrator action only).

        The only way a company code is ever changed (see
        ``ui.settings``) — there is no in-place "switch companies"
        operation. After this call the next application startup goes
        through the full first-run flow (company code + username +
        password) exactly like a brand-new installation; the
        previously registered device row is simply abandoned on the
        server (no deregistration API exists to reclaim its slot).
        """
        with self._database.session_scope() as session:
            ClientSyncCredentialRepository(session).clear()

    def _auto_enroll(self, company_code: str) -> SubscriptionCheckResult | None:
        """Attempt fully-automatic self-registration to ``company_code``'s subscription.

        Returns:
            ``None`` on success (the caller falls through to a live
            status check); a blocking :class:`SubscriptionCheckResult`
            explaining why not, otherwise.
        """
        try:
            self._sync_coordinator.self_enroll(name=self._device_name, company_code=company_code)
            return None
        except MaxDevicesReachedError:
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.MAX_DEVICES_REACHED,
                allowed=False,
                message_ar="تم الوصول إلى الحد الأقصى للأجهزة المسموح بها. (Maximum allowed devices reached.)",
                message_en="Maximum allowed devices reached.",
            )
        except DeviceRegistrationRejectedError:
            # Deliberately the same generic outcome/message regardless of
            # whether the code doesn't exist or exists but is inactive --
            # see server.api.routers.devices' own docstring on why the
            # server itself never lets this client tell the two apart.
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.INVALID_COMPANY_CODE,
                allowed=False,
                message_ar="رمز الشركة غير صحيح أو غير فعّال. يرجى التحقق منه أو التواصل مع مسؤول النظام.",
                message_en="Invalid or inactive company code. Please check it or contact your administrator.",
            )
        except SyncClientError:
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.UNREACHABLE_BLOCKED,
                allowed=False,
                message_ar="تعذر الاتصال بخادم الحضور لتسجيل هذا الجهاز تلقائيًا.",
                message_en="Could not reach the Attendance Server to automatically register this installation.",
            )

    def _result_from_live_status(self, status: SubscriptionStatusResult) -> SubscriptionCheckResult:
        if status.status == "active":
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.VALID,
                allowed=True,
                message_ar="الاشتراك فعّال.",
                message_en="Subscription is active.",
                company_name=status.company_name,
                days_remaining=status.days_remaining,
            )
        if status.status == "suspended":
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.SUSPENDED,
                allowed=False,
                message_ar="تم إيقاف اشتراك الشركة. يرجى التواصل مع مزوّد الخدمة.",
                message_en="Company subscription is suspended. Please contact your provider.",
                company_name=status.company_name,
            )
        if status.status == "expired":
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.EXPIRED,
                allowed=False,
                message_ar="انتهت صلاحية الاشتراك. يرجى تجديد الاشتراك للمتابعة.",
                message_en="Subscription has expired. Please renew to continue.",
                company_name=status.company_name,
            )
        # status.status == "not_linked"
        return SubscriptionCheckResult(
            outcome=SubscriptionCheckOutcome.NOT_REGISTERED,
            allowed=False,
            message_ar="هذا الجهاز غير مرتبط باشتراك شركة على الخادم.",
            message_en="This installation is not linked to a company subscription on the server.",
        )

    def _evaluate_grace(self) -> SubscriptionCheckResult:
        """Fall back to the cached, last-confirmed status while the server is unreachable."""
        with self._database.session_scope() as session:
            cached = ClientSubscriptionStateRepository(session).get()

        if cached is None:
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.UNREACHABLE_BLOCKED,
                allowed=False,
                message_ar=(
                    "تعذر الاتصال بخادم الحضور للتحقق من الاشتراك، "
                    "ولا توجد بيانات اشتراك محفوظة من تحقق سابق."
                ),
                message_en=(
                    "Could not reach the Attendance Server to verify the subscription, "
                    "and no previously confirmed subscription is cached."
                ),
            )

        # An explicit suspended/expired/not-linked verdict always applies
        # immediately, cached or not -- grace only ever covers "the
        # server could not be reached," never "the server said no."
        if cached.status == "suspended":
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.SUSPENDED,
                allowed=False,
                message_ar="تم إيقاف اشتراك الشركة. يرجى التواصل مع مزوّد الخدمة.",
                message_en="Company subscription is suspended. Please contact your provider.",
                company_name=cached.company_name,
            )
        if cached.status == "expired":
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.EXPIRED,
                allowed=False,
                message_ar="انتهت صلاحية الاشتراك. يرجى تجديد الاشتراك للمتابعة.",
                message_en="Subscription has expired. Please renew to continue.",
                company_name=cached.company_name,
            )
        if cached.status == "not_linked":
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.NOT_REGISTERED,
                allowed=False,
                message_ar="هذا الجهاز غير مرتبط باشتراك شركة على الخادم.",
                message_en="This installation is not linked to a company subscription on the server.",
            )

        elapsed = _utc_now() - _as_aware_utc(cached.checked_at)
        if elapsed <= self._grace_period:
            remaining_days = (self._grace_period - elapsed).days
            return SubscriptionCheckResult(
                outcome=SubscriptionCheckOutcome.UNREACHABLE_WITHIN_GRACE,
                allowed=True,
                message_ar=(
                    "تعذر الاتصال بخادم الحضور للتحقق من الاشتراك. "
                    f"تم السماح بالدخول مؤقتًا (يتبقى من فترة السماح: {remaining_days} يوم)."
                ),
                message_en=(
                    "Could not reach the Attendance Server to verify the subscription. "
                    f"Temporary access granted ({remaining_days} day(s) of grace period remaining)."
                ),
                company_name=cached.company_name,
            )

        return SubscriptionCheckResult(
            outcome=SubscriptionCheckOutcome.UNREACHABLE_BLOCKED,
            allowed=False,
            message_ar="تعذر الاتصال بخادم الحضور للتحقق من الاشتراك، وانتهت فترة السماح المؤقتة.",
            message_en=(
                "Could not reach the Attendance Server to verify the subscription, "
                "and the temporary grace period has expired."
            ),
            company_name=cached.company_name,
        )
